Agr 487 orthology table
alliance-genome/agr_archive_initial_prototype pull request #376
Opened 2017-08-14 15:57 UTC by sibyl229

#AGR-487

Interactive filtering of the orthology table by:
- confidence/quality
- species
- method
- is best
- is best reverse

2017-08-14 18:14 UTC, paaatrick requested changes
This looks great! Just two minor things I noticed:

1) I think there might be a problem with the generation of `all_methods`. For example, if you look at /gene/RGD:61995 the "Methods" select box doesn't include "ZFIN" as an option. It didn't look like that was being intentionally excluded. 

2) It might be nice to have some kind of "nothing matches your filters" message (hopefully not those exact words 😁 ) in the table instead of just having no rows under the header.

2017-08-15 19:44 UTC, sibyl229 commented
Thanks @paaatrick ! The message is add to show "No ortholog matching your filter. Please try a less stringent filter." It's a bit verbose. I'm happy to change it, when someone comes up with a better one.

I filed an issue for the backend on the missing method ZFIN, https://agr-jira.atlassian.net/browse/AGR-499. The reason that I can't fix this on the client side is that the set of available methods is derived from the API JSON (by taking the union of predictionMethodsMatched, predictionMethodsNotCalled, and predictionMethodsNotMatched). I think it's better to have a single source of truth in the code.

Thank you.

2017-08-15 20:06 UTC, paaatrick approved these changes

2017-08-15 20:06 UTC, paaatrick commented
Love it 👍

2017-08-15 20:06 UTC, merged